### ISSUE TITLE
Footer Bug

### ISSUE THREAD

**Issue by ritik307** [ProjectSakura/maintainers#10]
**Describe the bug**

- [ ] Unnecessary footer left-right margin

![maintainer-footer](https://user-images.githubusercontent.com/22374829/117711076-6b931200-b1f0-11eb-923b-fd481257489d.PNG)

- [ ] Footer theme not matching the site.

![maintainer-project](https://user-images.githubusercontent.com/22374829/117711168-88c7e080-b1f0-11eb-942e-3bf184c3ebf8.PNG)

**To Reproduce**
Steps to reproduce the behaviour:
1. Run npm start

**Comment by ritik307** [comment]
@LordShenron @ArunTeltia I would like to work on this issue. kindly assign

**Comment by LordShenron** [comment]
Go ahead.
