### ISSUE TITLE
Improvising the site 

### ISSUE THREAD

**Issue by Samridhi-98** [ProjectSakura/maintainers#12]
**Describe the bug**
Improvising the site i.e maintainer and developer page

**To Reproduce**
1. Run npm start
2. Go to `localhost:3000`

**Requirements**

- [ ]  Update `project sakura` logo to the updated one.
- [ ]  Heading should `meet the maintainer` and `meet the developers`.
- [ ]   Card's button alignment should be center.
- [ ]  Uneven top margin on maintainer and developers page.

**Screenshots**

![image_2021_05_11T12_34_39_146Z](https://user-images.githubusercontent.com/54466041/117815917-98443980-b283-11eb-8304-bd87e954a6ad.png)

![image_2021_05_11T12_35_54_487Z](https://user-images.githubusercontent.com/54466041/117815926-9aa69380-b283-11eb-995a-8c7a5d8f7803.png)

**Comment by Samridhi-98** [comment]
@LordShenron  @ArunTeltia  I would like to work on it please assign it to me.

**Comment by LordShenron** [comment]
Go Ahead, assigned to you
