### ISSUE TITLE
FEATURES BOX improvement

### ISSUE THREAD

**Issue by kumarishalini6** [ProjectSakura/maintainers#17]
**Is your feature request related to a problem? Please describe.**
The features box should have some border , hover effect , and light background color. i want to work on this issue under GSSoC'21 participants.

**Comment by ArunTeltia** [comment]
I am not sure what feature box you are talking about can you share an image of this

**Comment by kumarishalini6** [comment]
![Project Sakura _ Feels Like Spring and 2 more pages - Personal - Microsoft​ Edge 5_14_2021 01_11_26 AM](https://user-images.githubusercontent.com/69043944/118262389-4d801880-b461-11eb-8666-1035fc5f4189.png)

**Comment by kumarishalini6** [comment]
I am talking about this boxes

**Comment by ArunTeltia** [comment]
Oho okay sorry you opened the issue in the wrong repo  its an issue for https://github.com/ProjectSakura/ProjectSakura.github.io repo 

BTW lets not waste time recreating the issue there do you want to work on this ?

**Comment by kumarishalini6** [comment]
ya sure

**Comment by ArunTeltia** [comment]
okay so you need to fork the above repo and you can create a pr there all the best
