### ISSUE TITLE
Deployment Script 

### ISSUE THREAD

**Issue by ArunTeltia** [ProjectSakura/maintainers#7]
We need a deployment script right now like the download page, because right now the one having access to master can deploy and we have to redeploy everytime we push code to master

**Comment by ArunTeltia** [comment]
Tagging all the affected persons from this issue 
@LordShenron @FireQueen-3010 @vedikaag99

**Comment by LordShenron** [comment]
Auto deploying of the changes have been started. Refer to the change -> https://github.com/ProjectSakura/maintainers/commit/b51c6cc993b70626626ea4d25262ecf28b69bebe
